### ISSUE TITLE
[ВОПРОС] Будет ли в будующем поддержка других языков?

### ISSUE THREAD

**Issue by TheDevisi** [daswer123/yandex-tts-free#1]
Проект очень интересный и круто работает с русским языком, и это идеальная вещь, но вопрос, будет ли поддержка например английского языка? 
Спасибо.

**Comment by daswer123** [comment]
Спасибо, нет именно текущий метод работает только с русским языком.

Однако я сейчас изучаю другой подход, он уже позволит работать со всеми языками в Yandex SpeachKit , но пока в процессе изучения.

**Comment by TheDevisi** [comment]
> Спасибо, нет именно текущий метод работает только с русским языком.
> 
> Однако я сейчас изучаю другой подход, он уже позволит работать со всеми языками в Yandex SpeachKit , но пока в процессе изучения.

Благодарю за ответ. Буду ждать! :)
